spring:
  application:
    name: ${SPRING_APP_NAME:springsecuritysec1}
#  security:
#    user:
#      name: ${SPRING_SECURITY_USER_NAME:admin}
#      password: ${SPRING_SECURITY_USER_PASSWORD:admin}
server:
  port: ${SERVER_PORT:8080}
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
